import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Header from "@/app/components/header/Header";


import ReactQueryProviders from "./ReactQueryProviders";


import "./globals.css";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Site for exchange as a test ",
  description: "Generated by create next app for exchange as a test",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazirmatn.className}>
      <body>
        <Header />
        <ReactQueryProviders>{children}</ReactQueryProviders>{" "}
      </body>
    </html>
  );
}
