import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "./ReactQueryProviders";
import Header from "@/header/Header";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazirmatn.className}>
      <body>
        <Header />
        <ReactQueryProviders>{children}</ReactQueryProviders>{" "}
        {/* 👈 اینجا پیچیدیمش */}
      </body>
    </html>
  );
}
